import Foundation

extension Cafe {
    static let sampleCafes: [Cafe] = [
        Cafe(
            id: UUID(uuidString: "c31f7050-5677-49d1-a3e0-df0c3b0fb001")!,
            name: "성수커피",
            address: "서울 성동구 성수동",
            category: "스페셜티",
            city: "성수",
            latitude: 37.5445,
            longitude: 127.0561,
            rating: 4.8,
            reviewCount: 128,
            priceNote: "1인 7천원대",
            signatureMenu: "플랫화이트",
            shortDescription: "균형 잡힌 원두와 차분한 좌석감이 강점인 스페셜티 카페",
            vibeTags: ["조용한", "작업하기 좋은", "원두 맛집"],
            features: ["에스프레소 베이스 음료 만족도가 높아요.", "혼자 방문하기 좋은 좌석 배치예요.", "짧게 머물며 커피를 즐기기 좋아요."],
            openHours: "매일 10:00 - 21:00"
        ),
        Cafe(
            id: UUID(uuidString: "c31f7050-5677-49d1-a3e0-df0c3b0fb002")!,
            name: "레이어드빈 성수",
            address: "서울 성동구 연무장길 23",
            category: "디저트",
            city: "성수",
            latitude: 37.5458,
            longitude: 127.0552,
            rating: 4.7,
            reviewCount: 81,
            priceNote: "1인 9천원대",
            signatureMenu: "바닐라빈 라떼",
            shortDescription: "층고 높은 공간감과 디저트 조합이 강점인 성수 감성 카페",
            vibeTags: ["디저트 맛집", "사진이 잘 나오는", "대화하기 좋은"],
            features: ["좌석이 넉넉해 2~3인 방문 만족도가 높아요.", "디저트와 커피 조합이 좋아 첫 방문 만족감이 커요.", "주말 오후에는 대기가 있을 수 있어요."],
            openHours: "매일 11:00 - 22:00"
        ),
        Cafe(
            id: UUID(uuidString: "c31f7050-5677-49d1-a3e0-df0c3b0fb003")!,
            name: "연남카페",
            address: "서울 마포구 연남동",
            category: "로스팅",
            city: "연남",
            latitude: 37.5651,
            longitude: 126.9234,
            rating: 4.6,
            reviewCount: 94,
            priceNote: "1인 8천원대",
            signatureMenu: "시그니처 라떼",
            shortDescription: "직접 로스팅한 원두 풍미와 밝은 무드가 살아 있는 로스터리",
            vibeTags: ["대화하기 좋은", "향이 좋은", "데이트 추천"],
            features: ["향 중심 원두를 좋아하면 만족도가 높아요.", "매장 분위기가 밝고 사진이 잘 나와요.", "주말에는 다소 붐빌 수 있어요."],
            openHours: "매일 11:00 - 22:00"
        ),
        Cafe(
            id: UUID(uuidString: "c31f7050-5677-49d1-a3e0-df0c3b0fb004")!,
            name: "골목필터 연남",
            address: "서울 마포구 동교로38길 18",
            category: "필터커피",
            city: "연남",
            latitude: 37.5638,
            longitude: 126.9261,
            rating: 4.7,
            reviewCount: 66,
            priceNote: "1인 8천원대",
            signatureMenu: "에티오피아 핸드드립",
            shortDescription: "필터 커피 선택 폭이 넓고 조용히 머물기 좋은 연남 골목 카페",
            vibeTags: ["조용한", "핸드드립", "혼자 가기 좋은"],
            features: ["원두 설명이 친절해서 취향 탐색에 좋아요.", "혼자 앉기 좋은 바 좌석이 있어요.", "대화보다는 커피 맛에 집중하기 좋은 분위기예요."],
            openHours: "월-토 12:00 - 20:30"
        ),
        Cafe(
            id: UUID(uuidString: "c31f7050-5677-49d1-a3e0-df0c3b0fb005")!,
            name: "망원카페",
            address: "서울 마포구 망원동",
            category: "브런치",
            city: "망원",
            latitude: 37.5565,
            longitude: 126.9018,
            rating: 4.5,
            reviewCount: 73,
            priceNote: "1인 1만원대",
            signatureMenu: "브런치 플레이트",
            shortDescription: "브런치와 커피를 함께 즐기기 좋은 여유로운 동네 카페",
            vibeTags: ["브런치", "주말 방문", "친구와 가기 좋은"],
            features: ["식사와 커피를 한 번에 해결하기 편해요.", "테이블 간격이 적당해 모임에 좋아요.", "오전 시간대 방문 만족도가 높아요."],
            openHours: "화-일 09:00 - 20:00"
        ),
        Cafe(
            id: UUID(uuidString: "c31f7050-5677-49d1-a3e0-df0c3b0fb006")!,
            name: "포인트오브뷰 망원",
            address: "서울 마포구 포은로 91",
            category: "작업형",
            city: "망원",
            latitude: 37.5552,
            longitude: 126.9031,
            rating: 4.4,
            reviewCount: 58,
            priceNote: "1인 7천원대",
            signatureMenu: "오트 라떼",
            shortDescription: "넓은 테이블과 차분한 소음도로 작업 수요가 높은 망원 카페",
            vibeTags: ["작업하기 좋은", "노트북 친화", "오래 머물기 좋은"],
            features: ["콘센트 좌석이 있어 작업 목적 방문이 많아요.", "오트 라떼와 디카페인 옵션 만족도가 좋아요.", "피크타임엔 노트북 좌석 경쟁이 있을 수 있어요."],
            openHours: "매일 10:30 - 21:30"
        )
    ]
}
